### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by jjhidalgar** [belsrc/express-ip-block#1]
Shouldn't default value for "allow" be false? In consistence with this module name it should be blocking by default instead of whitelisting. Good job, just an opinion!

**Comment by belsrc** [comment]
Depends on how you look at it, i guess? I initially made it as a whitelister, so only the passed values are allowed (blocks all by default). The allow variable is in reference to the IP list and the action to take with them. *Allow only the given IPs* => allow = true
